slogan: "It's a sunny day,aha~"

theme: bootstrap
inverse: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/liliechao
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My CSDN Blog"
    url: http://blog.csdn.net/u013830021
    intro: "My CSDN account."
    icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.ico
duoshuo_shortname:
toc: true
# Analytics
google_analytics:
  enable: true
  siteid: UA-100592085-1
baidu_tongji:
  enable: false
  siteid:

# search
swiftype_key: yB7DdN7Wxn6zSD5RGBZ1

# share widgets
bdshare: true
jiathis: false

